"""
Tests for jax6502/chacha20.py — ChaCha20 in pure JAX.

Validates against:
  1. RFC 7539 Section 2.3.2 test vector (the gold standard)
  2. Cross-validation with coin/chacha20.js reference outputs
  3. Stream consistency (multi-block vs single-block)
  4. Board-init parity with the JS implementation
"""

import jax
import jax.numpy as jnp
import numpy as np
import pytest

# Strict dtype promotion — catches accidental float64 / int32 mixing
jax.config.update("jax_numpy_dtype_promotion", "strict")

from jax6502.chacha20 import (
    chacha20_block,
    chacha20_stream,
    derive_nonce,
    generate_board_init,
    quarter_round,
    rotl32,
    seed_to_key,
)


# ── RFC 7539 §2.3.2 test vector ──────────────────────────────────────

# Key  = 00:01:02:…:1f
# Nonce = 00:00:00:09:00:00:00:4a:00:00:00:00  (LE uint32 words)
# Counter = 1

RFC_KEY_BYTES = bytes(range(32))
RFC_NONCE_BYTES = bytes([0, 0, 0, 9, 0, 0, 0, 0x4A, 0, 0, 0, 0])

# Expected output for counter=1 (from the RFC)
RFC_EXPECTED_BLOCK1 = bytes([
    0x10, 0xf1, 0xe7, 0xe4, 0xd1, 0x3b, 0x59, 0x15,
    0x50, 0x0f, 0xdd, 0x1f, 0xa3, 0x20, 0x71, 0xc4,
    0xc7, 0xd1, 0xf4, 0xc7, 0x33, 0xc0, 0x68, 0x03,
    0x04, 0x22, 0xaa, 0x9a, 0xc3, 0xd4, 0x6c, 0x4e,
    0xd2, 0x82, 0x64, 0x46, 0x07, 0x9f, 0xaa, 0x09,
    0x14, 0xc2, 0xd7, 0x05, 0xd9, 0x8b, 0x02, 0xa2,
    0xb5, 0x12, 0x9c, 0xd1, 0xde, 0x16, 0x4e, 0xb9,
    0xcb, 0xd0, 0x83, 0xe8, 0xa2, 0x50, 0x3c, 0x4e,
])


class TestRFC7539:
    """RFC 7539 Section 2.3.2 — the gold-standard test vector."""

    def test_block_counter1(self):
        key = jnp.frombuffer(RFC_KEY_BYTES, dtype=jnp.uint32)
        nonce = jnp.frombuffer(RFC_NONCE_BYTES, dtype=jnp.uint32)
        block = chacha20_block(key, jnp.uint32(1), nonce)
        assert bytes(np.asarray(block)) == RFC_EXPECTED_BLOCK1

    def test_stream_contains_block1(self):
        """chacha20_stream with 2 blocks should contain the RFC block at offset 64."""
        key = jnp.frombuffer(RFC_KEY_BYTES, dtype=jnp.uint32)
        nonce = jnp.frombuffer(RFC_NONCE_BYTES, dtype=jnp.uint32)
        stream = chacha20_stream(key, nonce, 2)
        assert bytes(np.asarray(stream[64:128])) == RFC_EXPECTED_BLOCK1


# ── Cross-validation with JS reference ───────────────────────────────

# Generated by running coin/chacha20.js via Node.js
JS_ZERO_BLOCK0 = [
    118, 184, 224, 173, 160, 241, 61, 144, 64, 93, 106, 229, 83, 134, 189,
    40, 189, 210, 25, 184, 160, 141, 237, 26, 168, 54, 239, 204, 139, 119,
    13, 199, 218, 65, 89, 124, 81, 87, 72, 141, 119, 36, 224, 63, 184, 216,
    74, 55, 106, 67, 184, 244, 21, 24, 161, 28, 195, 135, 182, 105, 178,
    238, 101, 134,
]

JS_SEED_KEY_TEST = [
    159, 134, 208, 129, 136, 76, 125, 101, 154, 47, 234, 160, 197, 90, 208,
    21, 163, 191, 79, 27, 43, 11, 130, 44, 209, 93, 108, 21, 176, 240, 10, 8,
]

JS_NONCE_SIZE8 = [44, 98, 66, 50, 205, 210, 33, 119, 18, 148, 223, 187]

JS_BOARD_INIT_FIRST64 = [
    178, 242, 76, 80, 138, 3, 70, 194, 187, 138, 128, 100, 150, 204, 89, 4,
    182, 109, 96, 3, 190, 113, 26, 165, 218, 40, 162, 5, 115, 247, 137, 10,
    222, 21, 58, 98, 143, 25, 174, 181, 130, 194, 112, 236, 141, 197, 90,
    200, 116, 216, 102, 195, 76, 39, 166, 66, 179, 23, 108, 140, 25, 167,
    130, 43,
]

JS_BOARD_INIT_LAST64 = [
    216, 163, 120, 121, 191, 107, 193, 51, 135, 176, 239, 142, 59, 134, 235,
    175, 176, 43, 187, 36, 79, 4, 200, 229, 52, 77, 176, 222, 175, 47, 17,
    88, 188, 28, 93, 139, 165, 53, 166, 148, 28, 245, 225, 53, 71, 84, 105,
    211, 154, 174, 112, 139, 89, 5, 163, 149, 214, 147, 112, 233, 194, 51,
    229, 220,
]


class TestCrossValidateJS:
    """Byte-for-byte match against coin/chacha20.js outputs."""

    def test_zero_key_nonce_block0(self):
        key = jnp.zeros(8, dtype=jnp.uint32)
        nonce = jnp.zeros(3, dtype=jnp.uint32)
        block = chacha20_block(key, jnp.uint32(0), nonce)
        assert list(np.asarray(block)) == JS_ZERO_BLOCK0

    def test_seed_to_key(self):
        key = seed_to_key("test")
        assert list(np.asarray(key).view(np.uint8)) == JS_SEED_KEY_TEST

    def test_derive_nonce(self):
        nonce = derive_nonce(8)
        assert list(np.asarray(nonce).view(np.uint8)) == JS_NONCE_SIZE8

    def test_board_init_first64(self):
        init = generate_board_init("test", 8)
        assert list(np.asarray(init[:64])) == JS_BOARD_INIT_FIRST64

    def test_board_init_last64(self):
        init = generate_board_init("test", 8)
        assert list(np.asarray(init[-64:])) == JS_BOARD_INIT_LAST64

    def test_board_init_length(self):
        init = generate_board_init("test", 8)
        assert len(init) == 8 * 8 * 1024


# ── Stream consistency ────────────────────────────────────────────────

class TestStreamConsistency:
    """First 64 bytes of a 128-byte stream must equal a standalone block."""

    def test_first_block_matches(self):
        key = jnp.zeros(8, dtype=jnp.uint32).at[0].set(jnp.uint32(42))
        nonce = jnp.zeros(3, dtype=jnp.uint32)
        stream = chacha20_stream(key, nonce, 2)
        single = chacha20_block(key, jnp.uint32(0), nonce)
        np.testing.assert_array_equal(
            np.asarray(stream[:64]), np.asarray(single)
        )


# ── Primitives ────────────────────────────────────────────────────────

class TestPrimitives:
    def test_rotl32(self):
        assert int(rotl32(jnp.uint32(1), jnp.uint32(1))) == 2
        assert int(rotl32(jnp.uint32(0x80000000), jnp.uint32(1))) == 1
        assert int(rotl32(jnp.uint32(0xDEADBEEF), jnp.uint32(16))) == 0xBEEFDEAD

    def test_quarter_round_rfc(self):
        """RFC 7539 Section 2.1.1 quarter-round test vector."""
        # The RFC specifies a 4-value test: a=0x11111111, b=0x01020304,
        # c=0x9b8d6f43, d=0x01234567 → QUARTERROUND(0,1,2,3)
        state = jnp.zeros(16, dtype=jnp.uint32)
        state = state.at[0].set(jnp.uint32(0x11111111))
        state = state.at[1].set(jnp.uint32(0x01020304))
        state = state.at[2].set(jnp.uint32(0x9B8D6F43))
        state = state.at[3].set(jnp.uint32(0x01234567))
        result = quarter_round(state, 0, 1, 2, 3)
        assert int(result[0]) == 0xEA2A92F4
        assert int(result[1]) == 0xCB1CF8CE
        assert int(result[2]) == 0x4581472E
        assert int(result[3]) == 0x5881C4BB


# ── Determinism ───────────────────────────────────────────────────────

class TestDeterminism:
    def test_same_inputs_same_output(self):
        key = jnp.zeros(8, dtype=jnp.uint32)
        nonce = jnp.zeros(3, dtype=jnp.uint32)
        a = chacha20_stream(key, nonce, 1)
        b = chacha20_stream(key, nonce, 1)
        np.testing.assert_array_equal(np.asarray(a), np.asarray(b))

    def test_different_keys_differ(self):
        nonce = jnp.zeros(3, dtype=jnp.uint32)
        k1 = jnp.zeros(8, dtype=jnp.uint32).at[0].set(jnp.uint32(1))
        k2 = jnp.zeros(8, dtype=jnp.uint32).at[0].set(jnp.uint32(2))
        a = chacha20_stream(k1, nonce, 1)
        b = chacha20_stream(k2, nonce, 1)
        assert not np.array_equal(np.asarray(a), np.asarray(b))
